apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="th">
    <head>
      <meta charset="UTF-8" />
      <title>Argo CD Auto SyncV5</title>
    </head>
    <body>
      <h1>ðŸš€ Argo CD Auto SyncV5</h1>
      <p>Version: v1</p>
    </body>
    </html>
